### ISSUE TITLE
Doesn't rebuild the toolchain, will eventually fail

### ISSUE THREAD

**Issue by BenWiederhake** [kleinesfilmroellchen/serenity-imager#1]
The CI rebuilds the Toolchain a lot. In fact, I agree that the Toolchain barely ever needs to be rebuilt. But there's also quite a few changes that really do necessitate rebuilds, and break everything loudly when that happens.

However, sometimes an outdated Toolchain results in a successful compilation that fails *only subtly*.

Therefore, you probably want to replace this with `./Meta/serenity.sh i686 rebuild-world` or something similar.

https://github.com/kleinesfilmroellchen/serenity-imager/blob/bc69263457ecf3b4d61bd3d195a0a8cfcbeee377/create_image.sh#L21

**Comment by kleinesfilmroellchen** [comment]
This in valid, but it may increase the imager rumtimes to significant numbers. My server currently manages seven minutes on a full build and I would prefer under half-an-hour. Im gonna do some tests and report back.

**Comment by BenWiederhake** [comment]
Since there's lots of manual setup anyway: Maybe rebuild the toolchain every week? Then only few images would be affected.
